# Generated by Django 4.2.7 on 2023-11-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userdata_signature_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='signature_file',
        ),
        migrations.AddField(
            model_name='userdata',
            name='signature_files',
            field=models.FileField(blank=True, null=True, upload_to='user_signatures/'),
        ),
    ]
