# Generated by Django 4.2.7 on 2023-11-13 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_userdata_signature_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_files', models.FileField(blank=True, null=True, upload_to='old_signatures/')),
                ('user_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.userdata')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_files', models.FileField(blank=True, null=True, upload_to='current_signatures/')),
                ('user_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.userdata')),
            ],
        ),
    ]
