# Generated by Django 4.2.7 on 2023-11-19 10:51

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_userdata_signature_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentsignature',
            name='signature_files',
            field=models.FileField(blank=True, null=True, upload_to=app.models.get_user_signature_path),
        ),
        migrations.AlterField(
            model_name='oldsignature',
            name='signature_files',
            field=models.FileField(blank=True, null=True, upload_to=app.models.get_user_signature_path),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='signature_files',
            field=models.FileField(blank=True, null=True, upload_to=app.models.get_user_signature_path),
        ),
    ]
