# Generated by Django 4.2.7 on 2023-11-21 12:41

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_currentsignature_signature_files_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_type', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to=app.models.get_user_signature_path)),
            ],
        ),
        migrations.RemoveField(
            model_name='currentsignature',
            name='signature_files',
        ),
        migrations.AlterField(
            model_name='currentsignature',
            name='user_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userdata'),
        ),
        migrations.RemoveField(
            model_name='oldsignature',
            name='signature_files',
        ),
        migrations.AlterField(
            model_name='oldsignature',
            name='user_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userdata'),
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='signature_files',
        ),
        migrations.AddField(
            model_name='currentsignature',
            name='signature_files',
            field=models.ManyToManyField(blank=True, to='app.signaturefile'),
        ),
        migrations.AddField(
            model_name='oldsignature',
            name='signature_files',
            field=models.ManyToManyField(blank=True, to='app.signaturefile'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='signature_files',
            field=models.ManyToManyField(blank=True, to='app.signaturefile'),
        ),
    ]
