# Generated by Django 4.2.7 on 2023-11-23 12:45

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_oldsignature_user_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=app.models.get_user_signature_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='signature_files',
        ),
        migrations.AddField(
            model_name='userdata',
            name='signature_files',
            field=models.ManyToManyField(blank=True, to='app.signaturefile'),
        ),
    ]
