# Generated by Django 5.0 on 2023-12-08 12:52

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_signature_files_userdata_signature_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='signature_10',
            field=models.FileField(blank=True, null=True, upload_to=app.models.get_user_signature_path),
        ),
        migrations.AddField(
            model_name='userdata',
            name='signature_11',
            field=models.FileField(blank=True, null=True, upload_to=app.models.get_user_signature_path),
        ),
        migrations.AddField(
            model_name='userdata',
            name='signature_12',
            field=models.FileField(blank=True, null=True, upload_to=app.models.get_user_signature_path),
        ),
        migrations.AddField(
            model_name='userdata',
            name='signature_13',
            field=models.FileField(blank=True, null=True, upload_to=app.models.get_user_signature_path),
        ),
        migrations.AddField(
            model_name='userdata',
            name='signature_14',
            field=models.FileField(blank=True, null=True, upload_to=app.models.get_user_signature_path),
        ),
        migrations.AddField(
            model_name='userdata',
            name='signature_15',
            field=models.FileField(blank=True, null=True, upload_to=app.models.get_user_signature_path),
        ),
        migrations.AddField(
            model_name='userdata',
            name='signature_16',
            field=models.FileField(blank=True, null=True, upload_to=app.models.get_user_signature_path),
        ),
        migrations.AddField(
            model_name='userdata',
            name='signature_17',
            field=models.FileField(blank=True, null=True, upload_to=app.models.get_user_signature_path),
        ),
        migrations.AddField(
            model_name='userdata',
            name='signature_18',
            field=models.FileField(blank=True, null=True, upload_to=app.models.get_user_signature_path),
        ),
        migrations.AddField(
            model_name='userdata',
            name='signature_19',
            field=models.FileField(blank=True, null=True, upload_to=app.models.get_user_signature_path),
        ),
        migrations.AddField(
            model_name='userdata',
            name='signature_20',
            field=models.FileField(blank=True, null=True, upload_to=app.models.get_user_signature_path),
        ),
        migrations.AddField(
            model_name='userdata',
            name='signature_21',
            field=models.FileField(blank=True, null=True, upload_to=app.models.get_user_signature_path),
        ),
        migrations.AddField(
            model_name='userdata',
            name='signature_22',
            field=models.FileField(blank=True, null=True, upload_to=app.models.get_user_signature_path),
        ),
        migrations.AddField(
            model_name='userdata',
            name='signature_23',
            field=models.FileField(blank=True, null=True, upload_to=app.models.get_user_signature_path),
        ),
        migrations.AddField(
            model_name='userdata',
            name='signature_24',
            field=models.FileField(blank=True, null=True, upload_to=app.models.get_user_signature_path),
        ),
        migrations.AddField(
            model_name='userdata',
            name='signature_25',
            field=models.FileField(blank=True, null=True, upload_to=app.models.get_user_signature_path),
        ),
        migrations.AddField(
            model_name='userdata',
            name='signature_4',
            field=models.FileField(blank=True, null=True, upload_to=app.models.get_user_signature_path),
        ),
        migrations.AddField(
            model_name='userdata',
            name='signature_5',
            field=models.FileField(blank=True, null=True, upload_to=app.models.get_user_signature_path),
        ),
        migrations.AddField(
            model_name='userdata',
            name='signature_6',
            field=models.FileField(blank=True, null=True, upload_to=app.models.get_user_signature_path),
        ),
        migrations.AddField(
            model_name='userdata',
            name='signature_7',
            field=models.FileField(blank=True, null=True, upload_to=app.models.get_user_signature_path),
        ),
        migrations.AddField(
            model_name='userdata',
            name='signature_8',
            field=models.FileField(blank=True, null=True, upload_to=app.models.get_user_signature_path),
        ),
        migrations.AddField(
            model_name='userdata',
            name='signature_9',
            field=models.FileField(blank=True, null=True, upload_to=app.models.get_user_signature_path),
        ),
    ]
