# Generated by Django 4.2.7 on 2023-12-12 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_userdata_signature_2_and_more'),
        ('app', '0013_userdata_signature_10_userdata_signature_11_and_more'),
    ]

    operations = [
    ]
