# Generated by Django 4.2.7 on 2023-12-12 16:18

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_merge_20231213_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='signature_2',
            field=models.FileField(blank=True, null=True, upload_to=app.models.get_user_signature_path),
        ),
        migrations.AddField(
            model_name='userdata',
            name='signature_3',
            field=models.FileField(blank=True, null=True, upload_to=app.models.get_user_signature_path),
        ),
    ]
