# Generated by Django 4.2.7 on 2023-11-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_oldsignature_currentsignature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='signature_files',
            field=models.FileField(blank=True, null=True, upload_to='stored_signatures/'),
        ),
    ]
