# Generated by Django 4.2.7 on 2023-11-23 12:55

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_signaturefile_remove_userdata_signature_files_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='signature_files',
        ),
        migrations.DeleteModel(
            name='SignatureFile',
        ),
        migrations.AddField(
            model_name='userdata',
            name='signature_files',
            field=models.FileField(blank=True, null=True, upload_to=app.models.get_user_signature_path),
        ),
    ]
